# Generated by Django 4.2.6 on 2023-10-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='packages',
            field=models.ManyToManyField(related_name='users', to='packages.package'),
        ),
    ]
